# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'closewidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(218, 114)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_mini = QtWidgets.QRadioButton(Dialog)
        self.button_mini.setMinimumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.button_mini.setFont(font)
        self.button_mini.setObjectName("button_mini")
        self.verticalLayout.addWidget(self.button_mini)
        self.button_close = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.button_close.setFont(font)
        self.button_close.setObjectName("button_close")
        self.verticalLayout.addWidget(self.button_close)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_confirm = QtWidgets.QPushButton(Dialog)
        self.button_confirm.setMaximumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.button_confirm.setFont(font)
        self.button_confirm.setFlat(True)
        self.button_confirm.setObjectName("button_confirm")
        self.horizontalLayout.addWidget(self.button_confirm)
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setMaximumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.button_cancel.setFont(font)
        self.button_cancel.setFlat(True)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_mini.setText(_translate("Dialog", "最小化至托盘"))
        self.button_close.setText(_translate("Dialog", "退出程序"))
        self.button_confirm.setText(_translate("Dialog", "确认"))
        self.button_cancel.setText(_translate("Dialog", "取消"))
