# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 515)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_Edit = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Edit.setObjectName("Button_Edit")
        self.gridLayout.addWidget(self.Button_Edit, 7, 0, 1, 1)
        self.Button_Create = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Create.setObjectName("Button_Create")
        self.gridLayout.addWidget(self.Button_Create, 2, 0, 1, 1)
        self.Button_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Delete.setObjectName("Button_Delete")
        self.gridLayout.addWidget(self.Button_Delete, 8, 0, 1, 1)
        self.Table_Schedule = QtWidgets.QTableWidget(self.centralwidget)
        self.Table_Schedule.setMouseTracking(True)
        self.Table_Schedule.setObjectName("Table_Schedule")
        self.Table_Schedule.setColumnCount(0)
        self.Table_Schedule.setRowCount(0)
        self.gridLayout.addWidget(self.Table_Schedule, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 742, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "备份计划"))
        self.Button_Edit.setText(_translate("MainWindow", "编辑计划"))
        self.Button_Create.setText(_translate("MainWindow", "新建计划"))
        self.Button_Delete.setText(_translate("MainWindow", "删除计划"))
